# SPDX-FileCopyrightText: 2025 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: CC-BY-4.0

{% set pdfium_max = environ["PDFIUM_MAX"] %}
{% set helpers_ver = environ["M_HELPERS_VER"] %}

package:
  name: pypdfium2_helpers
  version: {{ helpers_ver }}

source:
  git_url: ../../..

build:
  number: 0
  noarch: python
  entry_points:
    - pypdfium2 = pypdfium2.__main__:cli_main
  script_env:
    - PYPDFIUM_MODULES=helpers
  script:
    - {{ PYTHON }} conda/prepare_script.py
    - {{ PYTHON }} -m pip install . -v --no-deps --no-build-isolation

requirements:
  build:
    - git
    - python
    - pip
    - setuptools
    - wheel !=0.38.0,!=0.38.1
  run:
    # -- Reasons for pdfium version bounds --
    # >6635 : new pdfium errchecks
    # (before that: >6164 : API-breaking changes to ctypesgen)
    # !=6219 : Blacklisted due to https://crbug.com/pdfium/2112 (6205 is also affected, but not on conda due to monthly schedule)
    # <={{ pdfium_max }} : Prevents future versions for API safety reasons
    - python
    - pypdfium2-team::pypdfium2_raw >6635,!=6219,<={{ pdfium_max }}

test:
  requires:
    - pip
  imports:
    - pypdfium2
  commands:
    - pip check
    - pypdfium2 --help

about:
  summary: Python bindings to PDFium (helpers, external bindings)
  description: |
    This package provides python helpers around pdfium.
    Dependants are suggested to pin to a major version, but any tighter pinning is discouraged since it increases the risk for conflicts, and would lock you out from future fixes.
  license: BSD-3-Clause, Apache-2.0
  license_file:
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/Apache-2.0.txt
    - LICENSES/CC-BY-4.0.txt
  dev_url: https://github.com/pypdfium2-team/pypdfium2
  doc_url: https://pypdfium2.readthedocs.io

extra:
  recipe-maintainers:
    - pypdfium2-team
    - mara004
