# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: CC-BY-4.0

# NOTE: We mainly use dependabot for notification purposes (e.g. security updates, or just as a reminder to update all the locks & pins from time to time).
# For on-demand updates, please use `just refresh-all-pins`.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    cooldown:
      default-days: 14
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/lock"
    exclude-paths:
      - "lock/unmanaged/**"
    schedule:
      interval: "quarterly"
    cooldown:
      default-days: 7
    groups:
      python-packages:
        patterns:
          - "*"
