# SPDX-FileCopyrightText: 2024 GitHub
# SPDX-FileCopyrightText: 2025 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: CC-BY-4.0

# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    ignore:
      - dependency-name: "benc-uk/workflow-dispatch"
        versions: ["121"]  # presumably an upstream accident
