# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

# TODO migrate to pyproject.toml [project] table.
# Since module splitting (i.e. packaging pypdfium2_raw and helpers separately) was removed, we no longer need a dynamic project name, which was incompatible with [project] ("'name' is not allowed to be specified dynamically"). This had prevented us from an earlier migration.

[metadata]
long_description = file: README.md
long_description_content_type = text/markdown
author = pypdfium2-team
author_email = geisserml@gmail.com
url = https://github.com/pypdfium2-team/pypdfium2
project_urls =
    Source = https://github.com/pypdfium2-team/pypdfium2
    Tracker = https://github.com/pypdfium2-team/pypdfium2/issues
    Documentation = https://pypdfium2.readthedocs.io
    Changelog = https://pypdfium2.readthedocs.io/en/stable/changelog.html
keywords = pdf, pdfium
classifiers =
    # https://pypi.org/classifiers/
    Development Status :: 5 - Production/Stable
    Intended Audience :: Developers
    Intended Audience :: Information Technology
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: Implementation :: CPython
    Topic :: Multimedia :: Graphics
    Topic :: Software Development :: Libraries
