# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: 'Test one'
description: 'Test one wheel, with container/emulator if needed'
inputs:
  runner_os:
    required: true
  test_on_host:
    default: true
  docker:
    default: true
  docker_ignore_error:
    default: false
  auditwheel:
    default: true
  mac_universal:
    default: false

runs:
  using: 'composite'
  steps:
    
    # TODO test multiple python versions
    
    - name: Test wheel on host
      if: ${{ inputs.test_on_host }}
      shell: bash
      run: |
        python3 -m pip install -U -r req/test.txt
        python3 -m pip install dist/*.whl
        python3 -m pypdfium2_cli --version
        python3 -m pytest tests/ -sv
    
    - name: macOS - Test Intel under emulation
      if: ${{ startsWith(inputs.runner_os, 'macos-') && (inputs.mac_universal || !inputs.test_on_host) }}
      shell: bash
      # assuming python is universal (it should be)
      run: |
        arch -x86_64 python3 -m venv testenv
        PYTHON="arch -x86_64 ./testenv/bin/python3"
        $PYTHON -c "import platform as p; print(p.machine())"
        $PYTHON -m pip install dist/*.whl
        $PYTHON -m pip install -U -r req/test.txt
        $PYTHON -m pytest tests/ -sv
    
    - name: macOS - Show binary info
      if: ${{ startsWith(inputs.runner_os, 'macos-') }}
      shell: bash
      run: |
        PDFIUM_DLL="$(python3 -c "from pypdfium2_raw.bindings import _libs; print(_libs['pdfium']._name)")"
        vtool -show-build "$PDFIUM_DLL"
    
    - name: Linux - Set up QEMU (if needed)
      if: ${{ startsWith(inputs.runner_os, 'ubuntu-') && !inputs.test_on_host }}
      uses: docker/setup-qemu-action@v4
    
    - name: Linux - Test in Docker container
      if: ${{ startsWith(inputs.runner_os, 'ubuntu-') && inputs.docker }}
      continue-on-error: ${{ inputs.docker_ignore_error }}
      shell: bash
      # q&d: infer container target name from wheel name
      run: |
        WHEEL_PATH="$(ls dist/*.whl)"
        TARGET="$(python3 ./utils/regextract.py "-(\w+linux)_[\d_]+_(\w+)\." "%s_%s" "$WHEEL_PATH")"
        python3 ./utils/container_driver.py "$TARGET" -w "$WHEEL_PATH"
    
    - name: Linux - Run auditwheel show
      if: ${{ startsWith(inputs.os, 'ubuntu-') && inputs.auditwheel }}
      shell: bash
      run: |
        python3 -m pip install -U auditwheel
        python3 -m auditwheel show dist/*.whl
