# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: 'Install'
description: 'Install pip dependencies'

inputs:
  runner_os:
    description: 'Runner OS'
    default: ''
  pip_install:
    description: 'Arguments to pip install'
    default: ''
  pip_install_hot:
    description: 'Arguments to pip install (before dependency cooldown)'
    default: ''
  initial_python:
    description: 'The initial python executable to use'
    default: 'python3'

runs:
  using: 'composite'
  steps:
    
    - name: Create venv
      shell: bash
      run: |  # zizmor: ignore[github-env]
        $PYTHON -m venv .venv
        echo "${PWD}/.venv/${BIN_DIR_NAME}" >> "$GITHUB_PATH"
      env:
        PYTHON: ${{ inputs.initial_python }}
        # TODO(geisserml) confirm if this distinction is really necessary
        BIN_DIR_NAME: ${{ startsWith(inputs.runner_os, 'windows-') && 'Scripts' || 'bin' }}
    
    - name: Update pip itself
      shell: bash
      run: |
        which python3
        python3 -m pip install -U pip
    
    - name: Install with pip (cool)
      if: ${{ inputs.pip_install }}
      shell: bash
      run: python3 -m pip install $PIP_INSTALL
      env:
        PIP_INSTALL: ${{ inputs.pip_install }}
        # With some older versions of Python (e.g. 3.8), the max available pip version is incapable of dependency cooldown.
        # Since we still want to (or have to) test these versions, use $PIP_UPLOADED_PRIOR_TO rather than --uploaded-prior-to so the cooldown is just ignored if pip is too old.
        PIP_UPLOADED_PRIOR_TO: P8D
    
    - name: Install with pip (hot)
      if: ${{ inputs.pip_install_hot }}
      shell: bash
      run: python3 -m pip install $PIP_INSTALL_HOT
      env:
        PIP_INSTALL_HOT: ${{ inputs.pip_install_hot }}
    
    - name: Write cooldown to config
      shell: bash
      # NB: Like PIP_UPLOADED_PRIOR_TO, this will be silently ignored if pip is too old.
      run: python3 -m pip config set install.uploaded-prior-to P8D
