# SPDX-FileCopyrightText: 2023 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: CC-BY-4.0

name: PyPA package
description: Use this if you installed pypdfium2 from an **official PyPA package**

body:
  
  - type: textarea
    attributes:
      label: Description
      description: Please explain your problem
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Install Info
      render: shell
      description: |
        To provide information about your install, please run the following commands and paste the output below
        ```shell
        python -m pypdfium2 -v
        python -VV
        python -c "import platform as p; print(p.platform())"
        python -m pip show pypdfium2
        ```
    validations:
      required: true
  