# SPDX-FileCopyrightText: 2023 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: CC-BY-4.0

# TODO add separate template for source install issues?

# FIXME we'd like a slightly longer description, but GH seems to impose some length limit (undocumented?, feels like 200 chars or something?)
name: PyPA install
description: If you installed via pip (or other PyPA format tool), and encountered an issue while using the library. Use even if you believe it is not a package problem. Default template.

body:
  
  - type: checkboxes
    attributes:
      label: Package origin
      description: |
        There might be unofficial PyPA packages of pypdfium2 in the wild.
        **We do not support third-party builds, and they are not eligible for a bug report.** Please make sure to use our official packages.
      options:
        - label: I confirm to be using an **official package** of `pypdfium2` from `PyPI` or `GitHub/pypdfium2-team`.
          required: true
  
  - type: textarea
    attributes:
      label: Description
      description: Please explain your problem.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Install Info
      render: shell
      description: |
        To provide information about your install, please run the following commands and paste the output into the field below.
        **If you are not using pip, but another PyPA-compliant tool, replace the `pip show` call accordingly.**
        ```shell
        python -m pypdfium2 -v
        python -VV
        python -c "import platform as p; print(p.platform())"
        python -m pip show pypdfium2
        ```
    validations:
      required: true
  
  - type: checkboxes
    attributes:
      label: Validity
      options:
        - label: I confirm that I ran all commands, and pasted the whole output.
          required: true