# SPDX-FileCopyrightText: 2025 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: CC-BY-4.0

# TODO add separate template for source install issues?

# NOTE: GitHub seems to impose a length limit on the description (undocumented?, feels like 200 chars or something)
name: Installed from PyPI (DEFAULT template)
description: If you installed via pip (or similar), and encountered an issue while using the library. Use even if you believe it is not a package problem.

body:
  
  - type: checkboxes
    attributes:
      label: Checklist
      description: |
        There might be unofficial PyPA packages of pypdfium2 in the wild.
        **We do not support third-party builds, and they are not eligible for a bug report.** Please make sure to use our official packages.
      options:
        - label: I confirm to be using an **official package** of `pypdfium2` from `PyPI` or `GitHub/pypdfium2-team`.
          required: true
  
  - type: textarea
    attributes:
      label: Description
      description: Please explain your problem.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Install Info
      render: shell
      description: |
        To provide information about your install, please run the following commands and paste the output into the field below.
        If the install failed, the last 2 commands may be skipped.
        ```shell
        python -VV
        python -c "import platform as p; print(p.platform())"
        python -m pypdfium2 -v
        python -m pip show pypdfium2
        ```
    validations:
      required: true