# SPDX-FileCopyrightText: 2023 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: CC-BY-4.0

name: Conda install
description: If you installed via conda, and encountered an issue while using the library. Use even if you believe it is not a package problem.

body:
  
  # use a separate md section instead of a checklist description for better visibility since it's rather likely to come across an unofficial build with conda
  - type: markdown
    attributes:
      value: |
        #### Package origin
        There may be unofficial conda packages of pypdfium2/pdfium-binaries in other channels, including anaconda or conda-forge defaults. **We do not support third-party builds, and they are not eligible for a bug report.** Please use our official packages instead.
  
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have verified to be using the **official packages** from the `pypdfium2-team` and `bblanchon` channels.
          required: true
        - label: I confirm **requirements are satisfied** and **no conflicting builds** of pypdfium2/pdfium-binaries installed at the same time.
          required: true
        - label: I confirm to be working with the **conda env in question, and its proper python executable** (not system python).
          required: true
  
  - type: textarea
    attributes:
      label: Description
      description: Please explain your problem.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Install Info
      render: shell
      description: |
        To provide information about your install, please run the following commands and paste the output into the field below.
        ```shell
        python -m pypdfium2 -v
        which python
        python -VV
        python -c "import platform as p; print(p.platform())"
        python -m pip show pypdfium2_raw
        python -m pip show pypdfium2_helpers
        conda list --show-channel-urls "pypdfium2|pdfium-binaries"
        conda config --show-sources
        ```
    validations:
      required: true
  
  - type: checkboxes
    attributes:
      label: Validity
      options:
        - label: I confirm that I ran all commands in the conda env in question, with its proper python executable, and pasted the whole output.
          required: true