# SPDX-FileCopyrightText: 2023 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: CC-BY-4.0

# NOTE
# This is an attempt to bundle the pdfium binaries with conda packages, like we do for pypi wheels.
# However, conda does not support CPU specific but Python version independent packages, meaning we'd have to build for each Python separately, so the better solution is probably to unbundle pdfium.
# For now, let's retain this passively as a second option just in case a situation arises where bundling would be desired anyway.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

{% set helpers_ver = environ["M_HELPERS_VER"] %}
{% set git_depth = environ["M_GIT_DEPTH"] %}
{% set pl_spec = environ["IN_PDFIUM_PLATFORM"] %}
# {% set setup_cfg = load_file_data("setup.cfg") %}

package:
  name: pypdfium2_bundle
  version: {{ helpers_ver }}

source:
  git_url: ../../..
  git_depth: {{ git_depth }}

build:
  number: 0
  entry_points:
    - pypdfium2 = pypdfium2.__main__:cli_main
  script_env:
    - PDFIUM_PLATFORM=prepared!{{ pl_spec }}
  script:
    - {{ PYTHON }} conda/prepare_script.py
    - {{ PYTHON }} -m pip install . -v --no-deps --no-build-isolation

requirements:
  # NOTE conda theoretically offers an additional host section, but for our purposes this is effectively the same as the build section
  build:
    - git
    - python
    - pip
    - setuptools
    - wheel !=0.38.0,!=0.38.1
  run:
    - python

# pass --no-test if cross-building for non-host target
test:
  requires:
    - pip
    - pytest
    - pillow
    - numpy
  imports:
    - pypdfium2
    - pypdfium2_raw  # bundled
  source_files:
    - tests/
    - tests_old/
  commands:
    - pip check
    - pypdfium2 --help
    - pytest tests/ tests_old/

about:
  summary: Python bindings to PDFium (bundled helpers/binary/bindings)
  license: (Apache-2.0 OR BSD-3-Clause) AND LicenseRef-PdfiumThirdParty
  license-files:
    - LICENSES/Apache-2.0.txt
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/CC-BY-4.0.txt
    - LICENSES/LicenseRef-PdfiumThirdParty.txt
    - .reuse/dep5-wheel
  dev_url: https://github.com/pypdfium2-team/pypdfium2
  doc_url: https://pypdfium2.readthedocs.io

extra:
  recipe-maintainers:
    - pypdfium2-team
    - mara004
