# SPDX-FileCopyrightText: 2025 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: CC-BY-4.0

{% set pdfium_short = environ["PDFIUM_SHORT"] %}
{% set pdfium_full = environ["PDFIUM_FULL"] %}
{% set build_num = environ["BUILD_NUM"] %}

package:
  name: pypdfium2_raw
  version: {{ pdfium_short }}

source:
  git_url: ../../..

build:
  number: {{ build_num }}
  noarch: python
  script_env:
    - PYPDFIUM_MODULES=raw
    - PDFIUM_PLATFORM=system:{{ pdfium_short }}
  script:
    - {{ PYTHON }} conda/prepare_script.py
    - {{ PYTHON }} -m pip install . -v --no-deps --no-build-isolation

requirements:
  build:
    - git
    - python
    - pip
    - setuptools
    - wheel !=0.38.0,!=0.38.1
  run:
    # Pin pdfium-binaries to an exact version to ensure bindings/binary ABI match.
    # As long as we rebuild pypdfium2_raw continuously in sync with pdfium-binaries, this should not become a flexibility problem.
    - python
    - bblanchon::pdfium-binaries =={{ pdfium_full }}

test:
  requires:
    - pip
    - python
  imports:
    - pypdfium2_raw
  source_files:
    - conda/raw/minitest.py
  commands:
    - pip check
    - python conda/raw/minitest.py

about:
  summary: Python bindings to PDFium (raw, external binary)
  description: |
    This package provides raw ctypes bindings to pdfium.
    Note, dependents should not pin this package to an exact version, as pypdfium2_raw itself pins pdfium-binaries for ABI safety reasons.
    In general, pypdfium2_helpers is the canonical package (i.e. roughly equivalent to pypdfium2 on PyPI), so it is recommended to depend on that rather than on pypdfium2_raw directly.
  license: BSD-3-Clause, Apache-2.0
  license_file:
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/Apache-2.0.txt
    - LICENSES/CC-BY-4.0.txt
  dev_url: https://github.com/pypdfium2-team/pypdfium2
  doc_url: https://pypdfium2.readthedocs.io

extra:
  recipe-maintainers:
    - pypdfium2-team
    - mara004
