# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: BSD testing
on:
  workflow_dispatch:

jobs:
  
  freebsd_lo:
    name: Install on FreeBSD with libreoffice pdfium
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out pypdfium2
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Test in FreeBSD VM
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: freebsd
          version: '15.0'
          architecture: 'x86-64'
          cpu_count: 4
          shell: bash
          sync_files: 'runner-to-vm'  # or true for bi-directional sync
          run: |
            set -x
            # sudo pkg update && sudo pkg upgrade -y
            sudo pkg install -y git libreoffice python3 devel/py-pip devel/py-setuptools graphics/py-pillow math/py-numpy devel/py-pytest
            # ldd /usr/local/lib/libreoffice/program/libpdfiumlo.so
            # ldd /usr/local/lib/libopenjp2.so /usr/local/lib/libabsl_strings.so
            python3 -m pip config set global.break-system-packages true
            # facultative: set LD_PRELOAD just on bindings compile time so library loading will work. at runtime, workaround code in pypdfium2_raw's __init__.py takes over.
            export LD_PRELOAD="/usr/local/lib/libabsl_strings.so:/usr/local/lib/libopenjp2.so"
            python3 -m pip install -v .  # implies PDFIUM_PLATFORM=fallback -> system-search
            unset LD_PRELOAD
            python3 -m pypdfium2 --version
            python3 ./conda/raw/minitest.py
            # Some APIs are missing from libreoffice-pdfium, suppress known failure
            python3 -m pytest tests/ || true
