# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: CIBW one
on:
  workflow_call:
    inputs: &reusable_inputs
      runner_os:
        type: string
        required: true
      cibw_target:
        type: string
        required: true
      cibw_arch:
        type: string
        required: true
      cibw_py_ver:
        type: string
        default: 'cp314'
      pdfium_ver:
        type: string
        default: ''
      use_sysroot:
        type: boolean
        default: false
      test_pdfium:
        type: boolean
        default: true
      ref:
        type: string
        default: ''
      replicate_tag:
        type: string
        default: ''
  workflow_dispatch:
    inputs: *reusable_inputs

permissions:
  contents: read

jobs:
  
  build:
    name: ${{ inputs.cibw_target }} on ${{ inputs.runner_os }}
    runs-on: ${{ inputs.runner_os }}
    
    steps:
      
      - name: Check out pypdfium2 (deep)
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0  # for git describe
          persist-credentials: false
          ref: ${{ inputs.ref || github.ref_name }}
      
      - name: Prepare
        uses: ./.github/actions/prepare_one
        with:
          replicate_tag: ${{ inputs.replicate_tag }}
      
      - name: Set up QEMU
        if: ${{ contains(inputs.cibw_target, 'linux') && !(inputs.cibw_arch == 'x86_64' || inputs.cibw_arch == 'aarch64') }}
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      
      - name: Install Windows cross deps
        if: ${{ startsWith(inputs.runner_os, 'windows') && inputs.cibw_arch != 'AMD64' }}
        uses: ChristopheLav/windows-sdk-install@aceebd61475568479ce68465d0849f5de9a0bfe9 # v1.0.5
        with:
          version-sdk: 26100
          features: 'OptionId.WindowsDesktopDebuggers'
      
      - name: Download clang image
        if: ${{ contains(inputs.cibw_target, 'linux') && contains(fromJSON('["ppc64le","riscv64","loongarch64","s390x"]'), inputs.cibw_arch) }}
        run: bash utils/install-static-clang.sh -d ./clang_image -m download-only
      
      # Reminder: most configuration is in pyproject.toml so we can use TOML overrides
      - name: Build wheels
        uses: loong64/cibuildwheel@e2eb224eba52e082e342e0d7d7e1443a22a170f2 # v4.1.0
        env:
          # Will be tagged as not python specific by our setup.py. inputs.cibw_py_ver only controls the version used at build time.
          # Could also use `*`, then cibuildwheel would build with the oldest supported version, and walk through the others but skip because a compatible wheel is around already.
          CIBW_BUILD: "${{ inputs.cibw_py_ver }}-${{ inputs.cibw_target }}"
          CIBW_ARCHS: "${{ inputs.cibw_arch }}"
          PDFIUM_VER: "${{ inputs.pdfium_ver }}"
          USE_SYSROOT: "${{ inputs.use_sysroot && 1 || 0 }}"
          TEST_PDFIUM: "${{ inputs.test_pdfium && 1 || 0 }}"
        with:
          output-dir: wheelhouse
      
      - name: Upload wheel as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: ./wheelhouse/*.whl
          name: cibw-${{ inputs.cibw_target }}
      
      # CIBW does not support custom test containers: https://github.com/pypa/cibuildwheel/discussions/2553
      # So let's just do it on our own; we need container_driver.py for SBUILD and PBIN anyway. Notes:
      # - x86_64 and aarch64 (manylinux and musllinux) are already handled within cibuildwheel, but doesn't harm to test again in a different container
      # - Suppress known test suite failures on s390x and musllinux_armv7l
      - name: Post-test
        if: ${{ contains(inputs.cibw_target, 'linux') }}
        continue-on-error: ${{ inputs.cibw_arch == 's390x' || inputs.cibw_target == 'musllinux_armv7l' }}
        run: python3 utils/container_driver.py "$TARGET" -w wheelhouse/*.whl
        env:
          TARGET: ${{ inputs.cibw_target }}
