# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Conda packaging
on:
  workflow_call:
    inputs: &reusable_inputs
      package:
        type: string  # choices: "raw" or "helpers"
        required: true
      py_ver:
        type: string
        # AOTW, conda still has some problems with 3.13 and 3.14
        default: '3.12'
      pdfium_ver:
        type: string
        default: ''  # implies latest
      new_only:
        type: boolean
        default: true
      test:
        type: boolean
        default: true
      publish:
        type: boolean
        default: false
      actually_publish:
        type: boolean
        default: false
      ref:
        type: string
        default: ''
    secrets:
      anaconda_api_token:
        description: 'Anaconda API token. Required if actually_publish is true.'
        required: false
  workflow_dispatch:
    inputs: *reusable_inputs

# This is required for setup-miniconda / conda init
# see https://github.com/conda-incubator/setup-miniconda#important
defaults:
  run:
    shell: bash -el {0}
permissions: {}

# Might be nice to support building both packages in one run and testing the helpers package with the newly-built raw package, but this would be fairly complicated.

jobs:
  
  build:
    name: Build conda pypdfium2_${{ inputs.package }}
    permissions:
      contents: read  # recommended by checkout action
    
    runs-on: ubuntu-slim
    steps:
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          auto-update-conda: true
          python-version: ${{ inputs.py_ver }}
          # priority: highest to lowest
          # https://github.com/conda-incubator/setup-miniconda/blob/3afdf12ae89a97ee81acc85f1490189fba144938/README.md#example-4-conda-options
          channels: pypdfium2-team,bblanchon,defaults
          channel-priority: strict
          show-channel-urls: true
      
      - name: Check out pypdfium2 (deep)
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0  # for git describe
          persist-credentials: false
          ref: ${{ inputs.ref || github.ref_name }}
      
      - name: Prepare
        run: |
          python -VV
          conda install -y conda-build conda-verify
          git config --global user.email "geisserml@gmail.com"
          git config --global user.name "geisserml"
      
      - name: Create venv & install pip packages
        uses: ./.github/actions/install_step
        with:
          pip_install: -U -r req/setup.txt
          initial_python: python
      
      - name: Build package
        run: python conda/craft_conda_pkgs.py "$PACKAGE" $VERSION_PARAM $MAYBE_NEW_ONLY
        env:
          PACKAGE: ${{ inputs.package }}
          VERSION_PARAM: ${{ inputs.pdfium_ver && format('--pdfium-ver {0}', inputs.pdfium_ver) }}
          MAYBE_NEW_ONLY: ${{ inputs.new_only && '--new-only' || '' }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: conda_package
          path: conda/${{ inputs.package }}/out/
  
  test:
    
    name: Test ${{ matrix.os }} with Py ${{ matrix.py }}
    if: ${{ inputs.test }}
    needs: build
    permissions:
      contents: read  # recommended by checkout action
    
    strategy:
      fail-fast: false
      matrix:
        # Can't test Windows 11 ARM64 because setup-miniconda doesn't support it AOTW
        # Also, stick with ubuntu-24.04 for now so we can keep testing python 3.8
        os: ['ubuntu-24.04', 'ubuntu-24.04-arm', 'macos-15-intel', 'macos-latest', 'windows-latest']
        py: ['3.8', '3.14']  # '3.9', '3.10', '3.11', '3.12', '3.13',
        exclude:
          - os: macos-15-intel
            py: '3.14'
        include:
          - os: macos-15-intel
            py: '3.12'
    
    runs-on: ${{ matrix.os }}
    steps:
      
      - name: Check out pypdfium2 (shallow)
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: ${{ inputs.ref || github.ref_name }}
      
      - name: Miniconda setup
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.py }}
          channels: defaults
      
      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: conda_package
          path: conda_dist/
      
      - name: Show debug info
        run: |
          python -VV
          ls -l conda_dist/
      
      # according to the docs, --override-channels disables searching config file channels, and -c options priority decreases from left to right
      - name: Install/Test raw package
        if: ${{ inputs.package == 'raw' }}
        run: |
          conda install -y pypdfium2_raw --override-channels -c ./conda_dist/ -c bblanchon -c defaults
          python utils/minitest.py
      
      - name: Install/Test helpers package
        if: ${{ inputs.package == 'helpers' }}
        run: |
          conda install -y pytest pillow numpy
          conda install -y pypdfium2_helpers --override-channels -c ./conda_dist/ -c pypdfium2-team -c bblanchon -c defaults
          pytest tests/
  
  publish:
    
    name: ${{ inputs.actually_publish && 'Publish to Anaconda (actually)' || 'Publish (dry run)' }}
    if: ${{ inputs.publish && !cancelled() && !contains(needs.*.result, 'failure') }}
    needs: [build, test]
    permissions:
      contents: read  # recommended by checkout action
    
    # TODO(geisserml) Should we refactor integration to attach at least pypdfium2_helpers to the GH release as well? pypdfium2_raw would be more of a problem though.
    
    runs-on: ubuntu-slim
    steps:
      
      - name: Miniconda setup
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.py }}
          channels: defaults  # no custom channels needed here
          channel-priority: strict
      
      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: conda_package
          path: conda_dist/
      
      - name: Install deps
        run: conda install -y "anaconda-client==1.14.1"
      
      - name: Upload to Anaconda
        if: ${{ inputs.actually_publish }}
        run: |
          ARTIFACT_PATH=conda_dist/noarch/pypdfium2_${PACKAGE}-*.conda
          anaconda --verbose upload $ARTIFACT_PATH
        env:
          PACKAGE: ${{ inputs.package }}
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
