# SPDX-FileCopyrightText: 2025 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Debug / Test
on:
  workflow_dispatch:
    inputs:
      test_var:
        default: "xxx"
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Test
        run: echo "Hello!"