# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Update Docs (GH Pages)

on:
  workflow_call:
    inputs: &reusable_inputs
      publish:
        type: boolean
        default: false
  workflow_dispatch:
    inputs: *reusable_inputs

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash
permissions: {}

jobs:
  
  build:
    name: Build docs
    permissions:
      contents: read  # recommended by checkout and setup-python actions
    
    runs-on: ubuntu-26.04
    steps:
      
      - name: Check out pypdfium2 (deep)
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0  # for git describe in conf.py
          persist-credentials: false
      
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.14'
          pip-install: -r req/docs.txt
      
      - name: Install pypdfium2
        run: python3 -m pip install -v .
      
      - name: Build documentation
        run: python3 -m sphinx -b html docs/source docs/build/html
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: 'docs/build/html'
  
  publish:
    name: Publish to GH Pages
    needs: build
    if: ${{ inputs.publish }}
    
    permissions:
      pages: write     # Deploy to GH pages
      id-token: write  # Deploy to GH pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-26.04
    steps:
      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
