# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

# Maintainer's note: This workflow is registered for trusted publishing on pypdfium2's PyPI page, by filename. So if this file shall be renamed, remember to update the filename in PyPI and TestPyPI settings as well.

name: Main packaging
on:
  workflow_dispatch:
    inputs:
      runner_os:
        type: string
        default: 'ubuntu-26.04'
      py_vers:
        type: string
        default: '3.8 3.11 3.14'
      profile:
        # see strategy/profiles.json for choices
        type: string
        default: ''
      pbin:
        type: string
        default: ''
      sbuild:
        type: string
        default: ''
      cibw:
        type: string
        default: ''
      autorelease:
        type: boolean
        default: true
      sdist:
        type: boolean
        default: true
      conda:
        type: boolean
        default: false
      gh_pages:
        type: boolean
        default: false
      publish:
        type: boolean
        default: false
      actually_publish:
        type: boolean
        default: false

defaults:
  run:
    shell: bash
permissions: {}

jobs:
  
  prepare:
    name: Prepare build (matrix, checks, autorelease)
    permissions:
      contents: write  # needed for push
    outputs:
      pbin_needed: ${{ steps.get_matrix.outputs.pbin_needed }}
      sbuild_needed: ${{ steps.get_matrix.outputs.sbuild_needed }}
      cibw_needed: ${{ steps.get_matrix.outputs.cibw_needed }}
      pbin_matrix: ${{ steps.get_matrix.outputs.pbin_matrix }}
      sbuild_matrix: ${{ steps.get_matrix.outputs.sbuild_matrix }}
      cibw_matrix: ${{ steps.get_matrix.outputs.cibw_matrix }}
      ref: ${{ steps.get_version.outputs.ref }}
      version: ${{ inputs.autorelease && steps.get_version.outputs.version || '' }}
      branch_name: ${{ inputs.autorelease && steps.autorelease.outputs.branch_name || '' }}
    
    runs-on: ${{ inputs.runner_os }}
    steps:
      
      - name: Check out pypdfium2
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: ${{ !inputs.autorelease && 1 || 0 }}
          persist-credentials: ${{ inputs.autorelease }}  # zizmor: ignore[artipacked]
      
      # run get_matrix.py using the runner's pre-installed python
      - name: Determine build matrix
        id: get_matrix
        run: python3 strategy/get_matrix.py $PROFILE_OPT $PYVERS_OPT --pbin $PBIN_TARGETS --sbuild $SBUILD_TARGETS --cibw $CIBW_TARGETS --reveal >> "$GITHUB_OUTPUT"
        env:
          PROFILE_OPT: ${{ inputs.profile && format('--profile {0}', inputs.profile) || '' }}
          PYVERS_OPT: ${{ inputs.py_vers && format('--py-vers {0}', inputs.py_vers) || '' }}
          PBIN_TARGETS: ${{ inputs.pbin }} 
          SBUILD_TARGETS: ${{ inputs.sbuild }}
          CIBW_TARGETS: ${{ inputs.cibw }}
      
      - name: Set up Python
        if: ${{ inputs.autorelease }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.14'
          pip-install: -U -r req/check.txt -r req/setup.txt -r req/test.txt
      
      - name: Checks & Autorelease
        if: ${{ inputs.autorelease }}
        id: autorelease
        run: |
          ./utils/check.sh
          git config user.email "geisserml@gmail.com"
          git config user.name "geisserml"
          python3 setupsrc/emplace.py auto:latest
          BRANCH_NAME="autorelease_tmp_${RUN_ID}"
          python3 setupsrc/autorelease.py --to-branch "$BRANCH_NAME"
          python3 -m pip install -v --no-build-isolation -e .
          python3 -m pytest tests/ -sv
          git push -u origin "$BRANCH_NAME"  # just the branch (not tag)
          echo "branch_name=${BRANCH_NAME}" >> "$GITHUB_OUTPUT"
        env:
          RUN_ID: ${{ github.run_id }}
      
      - name: Upload release notes
        if: ${{ inputs.autorelease }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: release_notes
          path: RELEASE.md
      
      - name: Determine ref/version
        id: get_version
        run: |
          echo "ref=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          echo "version=$(git describe --abbrev=0)" >> "$GITHUB_OUTPUT"
  
  
  sdist:
    name: Craft sdist
    needs: prepare
    if: ${{ inputs.sdist }}
    permissions:
      contents: read  # recommended by checkout and setup-python actions
    
    runs-on: 'ubuntu-24.04'
    steps:
      
      - name: Check out pypdfium2
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0  # for git describe
          persist-credentials: false
          ref: ${{ needs.prepare.outputs.ref }}
      
      - name: Prepare Python
        uses: ./.github/actions/prepare_step
        with:
          py_vers: ${{ inputs.py_vers }}
          pip_install: -U -r req/setup.txt
      
      - name: Build & test sdist
        run: |
          python3 setupsrc/craft.py --sdist
          python3 utils/multitest.py -w dist/pypdfium2-*.tar.gz --py-vers $PY_VERS
        env:
          PY_VERS: ${{ inputs.py_vers }}
      
      - name: Upload sdist
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sdist
          path: dist/pypdfium2-*.tar.gz
  
  
  pbin:
    name: PBIN ${{ matrix.pbin_target }} on ${{ matrix.runner_os }}
    needs: prepare
    if: ${{ fromJSON(needs.prepare.outputs.pbin_needed) }}
    permissions:
      contents: read  # needed by called workflow
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.pbin_matrix) }}
    
    uses: ./.github/workflows/pbin_one.yaml
    with:
      runner_os: ${{ matrix.runner_os }}
      test_os: ${{ matrix.test_os }}
      py_vers: ${{ matrix.py_vers }}
      testos_py_vers: ${{ matrix.testos_py_vers }}
      pbin_target: ${{ matrix.pbin_target }}
      test_on_host: ${{ matrix.test_on_host }}
      ref: ${{ needs.prepare.outputs.ref }}
      replicate_tag: ${{ needs.prepare.outputs.version }}
  
  
  sbuild:
    name: SBLD ${{ matrix.target_os || matrix.runner_os }} ${{ matrix.target_cpu }}
    needs: prepare
    if: ${{ fromJSON(needs.prepare.outputs.sbuild_needed) }}
    permissions:
      contents: read  # needed by called workflow
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.sbuild_matrix) }}
    
    uses: ./.github/workflows/sbuild_one.yaml
    with:
      runner_os: ${{ matrix.runner_os }}
      test_os: ${{ matrix.test_os }}
      py_vers: ${{ matrix.py_vers }}
      testos_py_vers: ${{ matrix.testos_py_vers }}
      # pdfium_ver: ${{ ... }}  # TODO
      target_os: ${{ matrix.target_os }}
      target_cpu: ${{ matrix.target_cpu }}
      build_params: ${{ matrix.build_params }}
      wheel_tag: ${{ matrix.tag }}
      ref: ${{ needs.prepare.outputs.ref }}
      replicate_tag: ${{ needs.prepare.outputs.version }}
  
  
  cibw:
    name: CIBW ${{ matrix.cibw_target }} on ${{ matrix.runner_os }}
    needs: prepare
    if: ${{ fromJSON(needs.prepare.outputs.cibw_needed) }}
    permissions:
      contents: read  # needed by called workflow
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.cibw_matrix) }}
    
    uses: ./.github/workflows/cibw_one.yaml
    with:
      runner_os: ${{ matrix.runner_os }}
      test_os: ${{ matrix.test_os }}
      # cibw_py_ver: ${{ ... }}  # TODO
      testos_py_vers: ${{ matrix.testos_py_vers }}
      cibw_target: ${{ matrix.cibw_target }}
      cibw_arch: ${{ matrix.cibw_arch }}
      # pdfium_ver: ${{ ... }}  # TODO
      use_sysroot: ${{ matrix.use_sysroot || false }}
      ref: ${{ needs.prepare.outputs.ref }}
      replicate_tag: ${{ needs.prepare.outputs.version }}
  
  
  publish:
    name: Publish to PyPI & GH
    needs: [prepare, sdist, pbin, sbuild, cibw]
    if: ${{ inputs.publish && !cancelled() && !contains(needs.*.result, 'failure') }}
    
    # environment: release  # PyPI upload  # XXX temporarily commented out
    permissions:
      id-token: write      # PyPI upload, GH attestation
      attestations: write  # GH attestation
      contents: write      # git push
    
    runs-on: ${{ inputs.runner_os }}
    steps:
      
      - name: Check out pypdfium2 (deep, authenticated)
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0  # for git describe
          persist-credentials: true  # zizmor: ignore[artipacked]
      
      - name: Download release notes
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: release_notes
      
      - name: Download sdist
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist/
          name: sdist
      
      - name: Download PBIN wheels
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist/
          merge-multiple: true
          pattern: pbin-*
      
      - name: Download SBLD wheels
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist/
          merge-multiple: true
          pattern: sbuild-*
      
      - name: Download CIBW wheels
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist/
          merge-multiple: true
          pattern: cibw-*
      
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.14'
          pip-install: -U -r req/distcheck.txt
      
      - name: Check artifacts
        run: |
          twine check dist/*
          check-wheel-contents dist/*.whl
      
      - name: Mask non-PyPI builds
        run: |
          mkdir artifacts/ && cp dist/* -t artifacts/
          shopt -s nullglob
          rm -f dist/*linux_*_loongarch64*.whl dist/*linux_*_mips64le*.whl dist/*linux_*_mipsle*.whl
      
      - name: Apply and push repository changes
        if: ${{ inputs.actually_publish }}
        run: |
          git config user.email "geisserml@gmail.com"
          git config user.name "geisserml"
          # TODO assert HEAD commit hash matches the autorelease commit (no tampering)
          git checkout main
          git merge "origin/${BRANCH_NAME}"
          git tag -a "$NEW_VERSION" -m "Autorelease"
          git push
          git push --tags
          git checkout stable
          git reset --hard main
          git push --force
          git checkout main
        env:
          NEW_VERSION: ${{ needs.prepare.outputs.version }}
          BRANCH_NAME: ${{ needs.prepare.outputs.branch_name }}
      
      - name: Attest build provenance
        if: ${{ inputs.actually_publish }}
        id: provenance
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
        with:
          subject-path: 'artifacts/*'
      
      - name: Rename provenance file
        if: ${{ inputs.actually_publish }}
        run: mv "$SRC_PATH" pypdfium2-attestation.json
        env:
          SRC_PATH: ${{ steps.provenance.outputs.bundle-path }}
      
      - name: Publish to PyPI
        if: ${{ inputs.actually_publish }}
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          packages-dir: dist/  # the default
          # skip-existing: true
      
      - name: Publish to GitHub
        if: ${{ inputs.actually_publish }}
        run: gh release create "$TAG" --notes-file RELEASE.md --verify-tag --fail-on-no-commits $BETA_FLAG artifacts/* pypdfium2-attestation.json
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ needs.prepare.outputs.version }}
          BETA_FLAG: ${{ contains(needs.prepare.outputs.version, 'b') && '--prerelease' || '' }}
  
  
  gh_pages:
    name: GH Pages
    needs: publish  # i.e. goes after, regardless if publish is active or not
    if: ${{ inputs.gh_pages && !cancelled() && !contains(needs.*.result, 'failure') }}
    permissions:
      contents: read   # needed by called workflow
      pages: write     # dto.
      id-token: write  # dto.
    
    uses: ./.github/workflows/gh_pages.yaml
    with:
      publish: ${{ inputs.publish }}
  
  
  conda:
    name: Trigger conda pypdfium2_helpers
    needs: publish
    if: ${{ inputs.conda && !cancelled() && !contains(needs.*.result, 'failure') }}
    permissions:
      actions: write  # needed by dispatch.yaml
    
    uses: ./.github/workflows/dispatch.yaml
    with:
      workflow_file: conda.yaml
      inputs: |
        {
          "package": "helpers",
          "py_ver": "3.12",
          "pdfium_ver": "",
          "new_only": "true",
          "test": "true",
          "publish": "${{ inputs.publish }}",
          "actually_publish": "${{ inputs.actually_publish }}"
        }
  
  
  cleanup:
    name: Clean up temporary branch
    needs: [prepare, publish, gh_pages, conda]
    if: ${{ inputs.autorelease && !cancelled() }}
    permissions:
      contents: write  # needed for push
    
    runs-on: ${{ inputs.runner_os }}
    steps:
      
      - name: Check out pypdfium2 (shallow, authenticated)
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: true  # zizmor: ignore[artipacked]
    
      - name: Remove temporary branch
        run: git push origin --delete "$BRANCH_NAME"
        env:
          BRANCH_NAME: ${{ needs.prepare.outputs.branch_name }}
