# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

# Maintainer's note: This workflow is registered for trusted publishing on pypdfium2's PyPI page, by filename. So if this file shall be renamed, remember to update the filename in PyPI and TestPyPI settings as well.

name: Main packaging
on:
  workflow_dispatch:
    inputs:
      runner_os:
        type: string
        default: 'ubuntu-26.04'
      py_ver:
        type: string
        default: '3.14'
      profile:
        # see strategy/profiles.json for choices
        type: string
        default: ''
      pbin:
        type: string
        default: ''
      sbuild:
        type: string
        default: ''
      cibw:
        type: string
        default: ''
      checks:
        type: boolean
        default: true
      autorelease:
        type: boolean
        default: true
      conda:
        type: boolean
        default: false
      gh_pages:
        type: boolean
        default: false
      publish:
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:  
  
  prepare:
    runs-on: ${{ inputs.runner_os }}
    outputs:
      pbin_needed: ${{ steps.get_matrix.outputs.pbin_needed }}
      sbuild_needed: ${{ steps.get_matrix.outputs.sbuild_needed }}
      cibw_needed: ${{ steps.get_matrix.outputs.cibw_needed }}
      pbin_matrix: ${{ steps.get_matrix.outputs.pbin_matrix }}
      sbuild_matrix: ${{ steps.get_matrix.outputs.sbuild_matrix }}
      cibw_matrix: ${{ steps.get_matrix.outputs.cibw_matrix }}
      ref: ${{ steps.get_version.outputs.ref }}
      version: ${{ steps.get_version.outputs.version }}
    
    # avoid the need to allocate separate runners & try to share as much as possible
    # this goes at the cost of some fragmentation
    
    steps:
      
      - name: Check out pypdfium2 (shallow, authenticated=${{ inputs.autorelease }})
        uses: actions/checkout@v6
        with:
          fetch-depth: 1  # unshallowed below, if needed
          persist-credentials: ${{ inputs.autorelease }}  # for push
      
      - name: Set up Python
        if: ${{ inputs.py_ver && (inputs.checks || inputs.autorelease) }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.py_ver }}
      
      - name: Set up Just
        if: ${{ inputs.checks }}
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3  # v4.0.0
      
      - name: Determine build matrix
        id: get_matrix
        run: python3 strategy/get_matrix.py $PROFILE_OPT --pbin $PBIN_TARGETS --sbuild $SBUILD_TARGETS --cibw $CIBW_TARGETS --reveal >> "$GITHUB_OUTPUT"
        env:
          PROFILE_OPT: ${{ inputs.profile && format('--profile {0}', inputs.profile) || '' }}
          PBIN_TARGETS: ${{ inputs.pbin }} 
          SBUILD_TARGETS: ${{ inputs.sbuild }}
          CIBW_TARGETS: ${{ inputs.cibw }}
      
      - name: Install common dependencies
        if: ${{ inputs.checks || inputs.autorelease }}
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -U -r req/setup.txt
      
      - name: Run pre-release checks
        if: ${{ inputs.checks }}
        run: |
          python3 -m pip install -U -r req/check.txt
          just check
          git fetch --unshallow
      
      - name: Run autorelease script
        if: ${{ inputs.autorelease }}
        run: |
          git config user.email "geisserml@gmail.com"
          git config user.name "geisserml"
          # autorelease.py --register automatically switches to the autorelease_tmp branch
          python3 setupsrc/autorelease.py --register
      
      - name: Pack sdist
        if: ${{ inputs.checks || inputs.autorelease }}
        run: python3 setupsrc/craft.py --sdist
      
      - name: Run test suite
        if: ${{ inputs.checks }}
        run: |
          python3 -m pip install -v dist/pypdfium2-*.tar.gz
          python3 -m pip install -U -r req/test.txt
          python3 -m pytest tests/ -sv
      
      - name: Determine ref/version
        id: get_version
        # XXX git describe will return false with shallow checkout
        run: |
          echo "ref=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          echo "version=$(git describe --abbrev=0)" >> "$GITHUB_OUTPUT"
      
      - name: Upload sdist
        if: ${{ inputs.autorelease }}
        uses: actions/upload-artifact@v7
        with:
          name: sdist
          path: dist/pypdfium2-*.tar.gz
      
      - name: Upload release notes
        if: ${{ inputs.autorelease }}
        uses: actions/upload-artifact@v7
        with:
          name: release_notes
          path: RELEASE.md
      
      # tag intentionally not pushed
      - name: Push autorelease_tmp branch
        if: ${{ inputs.autorelease }}
        run: git push -u origin autorelease_tmp
  
  
  pbin:
    
    needs: prepare
    if: ${{ needs.prepare.outputs.pbin_needed }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.pbin_matrix) }}
    
    uses: ./.github/workflows/pbin_one.yaml
    with:
      runner_os: ${{ matrix.runner_os }}
      pbin_target: ${{ matrix.pbin_target }}
      # py_vers: ${{ ... }}  # TODO
      test_on_host: ${{ matrix.test_on_host }}
      ref: ${{ needs.prepare.outputs.ref }}
      replicate_tag: ${{ inputs.autorelease && needs.prepare.outputs.version }}
  
  
  sbuild:
    needs: prepare
    if: ${{ needs.prepare.outputs.sbuild_needed }}
    
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.sbuild_matrix) }}
    
    uses: ./.github/workflows/sbuild_one.yaml
    with:
      os: ${{ matrix.runner_os }}
      # py_vers: ${{ ... }}  # TODO
      target_cpu: ${{ matrix.target_cpu }}
      target_os: ${{ matrix.target_os }}
      build_params: ${{ matrix.build_params }}
      custom_clang: ${{ matrix.custom_clang || false }}
      wheel_tag: ${{ matrix.tag }}
      ref: ${{ needs.prepare.outputs.ref }}
      replicate_tag: ${{ inputs.autorelease && needs.prepare.outputs.version }}
  
  
  cibw:
    needs: prepare
    if: ${{ needs.prepare.outputs.cibw_needed }}
    
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.cibw_matrix) }}
    
    uses: ./.github/workflows/cibw_one.yaml
    with:
      runner_os: ${{ matrix.runner_os }}
      cibw_target: ${{ matrix.cibw_target }}
      cibw_arch: ${{ matrix.cibw_arch }}
      # cibw_py_ver: ${{ ... }}  # TODO
      # pdfium_ver: ${{ ... }}  # TODO
      use_sysroot: ${{ matrix.use_sysroot || false }}
      ref: ${{ needs.prepare.outputs.ref }}
      replicate_tag: ${{ inputs.autorelease && needs.prepare.outputs.version }}
  
  
  publish:
    
    needs:
      - prepare
      - pbin
      - cibw
      - sbuild
    
    if: ${{ inputs.publish && !cancelled() && !contains(needs.*.result, 'failure') }}
    runs-on: ${{ inputs.runner_os }}
    
    environment: release  # PyPI upload via "trusted publishing"
    permissions:
      id-token: write      # PyPI upload via "trusted publishing", and GH attestation
      attestations: write  # GH attestation
      contents: write      # autorelease repository changes
      actions: write       # GH pages build
    
    steps:
      
      - name: Check out pypdfium2 (deep, authenticated)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # for git describe
          persist-credentials: true  # for push
      
      - name: Set up Python
        if: ${{ inputs.py_ver }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.py_ver }}
      
      - name: Download release notes
        uses: actions/download-artifact@v8
        with:
          name: release_notes
      
      - name: Download sdist
        uses: actions/download-artifact@v8
        with:
          name: sdist
      
      - name: Download PBIN wheels
        uses: actions/download-artifact@v8
        with:
          path: dist/
          merge-multiple: true
          pattern: pbin-*
      
      - name: Download SBLD wheels
        uses: actions/download-artifact@v8
        with:
          path: dist/
          merge-multiple: true
          pattern: sbuild_*  # XXX
      
      - name: Download CIBW wheels
        uses: actions/download-artifact@v8
        with:
          path: dist/
          merge-multiple: true
          pattern: cibw-*
      
      - name: Isolate non-PyPI builds
        # if: XXX
        run: |
          mkdir gh_only
          mv dist/*linux_*_loongarch64*.whl -t gh_only/
          mv dist/*linux_*_mips64le*.whl dist/*linux_*_mipsle*.whl -t gh_only/
      
      - name: Apply and push repository changes
        run: |
          git config user.email "geisserml@gmail.com"
          git config user.name "geisserml"
          # TODO assert HEAD commit hash matches the autorelease commit (no tampering)
          git checkout main
          git merge origin/autorelease_tmp
          git tag -a "$NEW_VERSION" -m "Autorelease"
          git push
          git push --tags
          git checkout stable
          git reset --hard main
          git push --force
          git checkout main
        env:
          NEW_VERSION: ${{ needs.prepare.outputs.version }}
      
      # Upload to TestPyPI / PyPI via "trusted publishing".
      # https://docs.pypi.org/trusted-publishers/adding-a-publisher/
      # https://docs.pypi.org/trusted-publishers/using-a-publisher/
      # https://github.com/pypa/gh-action-pypi-publish
      
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/  # the default
          # https://github.com/pypa/gh-action-pypi-publish/issues/283#issuecomment-2499296440
          attestations: false
          verbose: true
      
      - name: Attest build provenance
        id: provenance
        uses: actions/attest-build-provenance@v4
        with:
          subject-path: 'dist/*, gh_only/*'
      
      - name: Rename provenance file
        run: mv "$SRC_PATH" pypdfium2-attestation.json
        env:
          SRC_PATH: ${{ steps.provenance.outputs.bundle-path }}
      
      # FIXME skip gh_only/*.whl if it does not exist
      - name: Publish to GitHub
        uses: ncipollo/release-action@v1  # TODO pin to hash?
        with:
          immutableCreate: true
          artifacts: 'dist/*.whl,gh_only/*.whl,dist/*.tar.gz,pypdfium2-attestation.json'
          bodyFile: 'RELEASE.md'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.prepare.outputs.version }}
          prerelease: ${{ contains(needs.prepare.outputs.version, 'b') }}
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/  # the default
  
  
  gh_pages:
    needs: publish  # i.e. goes after, regardless if publish is active or not
    if: ${{ inputs.gh_pages && !cancelled() && !contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/gh_pages.yaml
    with:
      publish: ${{ inputs.publish }}
  
  
  conda:
    needs: publish
    if: ${{ inputs.conda && !cancelled() && !contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/conda.yaml
    secrets: inherit  # Anaconda API token
    with:
      package: helpers
      test: true
      publish: ${{ inputs.publish }}
      # py_ver: ${{ inputs.py_ver }}  # temporarily downgraded
  
  
  cleanup:
    needs: [publish, gh_pages, conda]
    if: ${{ !cancelled() }}
    runs-on: ${{ inputs.runner_os }}
    
    steps:
      
      - name: Check out pypdfium2 (shallow, authenticated)
        uses: actions/checkout@v6
        with:
          persist-credentials: true  # for push
    
      - name: Remove temporary branch
        run: git push origin --delete autorelease_tmp
