# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Test Native Build one

on:
  workflow_call:
    inputs: &reusable_inputs
      runner_os:
        type: string
        required: true
      compiler:
        type: string
        default: gcc
      py_ver:
        type: string
        default: '3.14'
      pdfium_ver:
        type: string
        default: ''
      vendor:
        type: string
        default: 'icu'
      test_pdfium:
        type: boolean
        default: true
      condition:
        type: boolean
        default: true
  workflow_dispatch:
    inputs: *reusable_inputs

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  
  build:
    name: Native build on ${{ inputs.runner_os }} with ${{ inputs.compiler }}
    if: ${{ inputs.condition }}
    permissions:
      contents: read  # recommended by checkout and setup-python actions
    
    runs-on: ${{ inputs.runner_os }}
    steps:
      
      - name: Check out pypdfium2 (deep)
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0  # for git describe
          persist-credentials: false
      
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ inputs.py_ver }}
          pip-install: -U -r req/setup.txt -r req/test.txt
      
      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libfreetype-dev liblcms2-dev libjpeg-dev libopenjp2-7-dev libpng-dev zlib1g-dev libicu-dev libtiff-dev libglib2.0-dev libharfbuzz-dev  # generate-ninja
          python3 -m pip install -r req/gn.txt
      
      # TODO update to ubuntu 26.04 default clang ...
      - name: Set up symlinks for clang
        if: ${{ inputs.compiler == 'clang' }}
        run: |
          sudo apt-get install -y llvm lld
          VERSION=18 ARCH=$(uname -m)
          sudo ln -s /usr/lib/clang/$VERSION/lib/linux /usr/lib/clang/$VERSION/lib/$ARCH-unknown-linux-gnu
          sudo ln -s /usr/lib/clang/$VERSION/lib/linux/libclang_rt.builtins-$ARCH.a /usr/lib/clang/$VERSION/lib/linux/libclang_rt.builtins.a
      
      - name: Build PDFium (native, ${{ inputs.compiler }})
        run: python3 ./setupsrc/build_native.py --compiler "$COMPILER" $VERSION_PARAM $VENDOR_PARAM $TEST_PARAM
        env:
          COMPILER: ${{ inputs.compiler }}
          VERSION_PARAM: ${{ inputs.pdfium_ver && format('--version {0}', inputs.pdfium_ver) }}
          VENDOR_PARAM: ${{ inputs.vendor && format('--vendor {0}', inputs.vendor) }}
          TEST_PARAM: ${{ inputs.test_pdfium && '--test' || '' }}
      
      - name: Show binary info
        run: file data/sourcebuild/*pdfium.*
      
      - name: Build wheel
        run: python3 -m build -wxn
        env:
          PDFIUM_PLATFORM: sourcebuild
      
      - name: Post-process with auditwheel
        run: |
          python3 -m pip install -U auditwheel
          python3 -m auditwheel repair dist/*.whl -w wheelhouse
      
      - name: Upload wheel as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: ./wheelhouse/*.whl
          name: "native-${{ inputs.compiler }}_${{ inputs.runner_os }}"
      
      - name: Install and test wheel
        run: |
          python3 -m pip install ./wheelhouse/*.whl
          pypdfium2 -v
          python3 -m pytest tests/
