# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: PBIN one
on:
  workflow_call:
    inputs: &reusable_inputs
      runner_os:
        type: string
        required: true
      test_os:
        type: string
        default: ''
      py_vers:
        type: string
        default: '3.14'
      testos_py_vers:
        type: string
        default: ''
      pbin_target:
        type: string
        default: ''
      pdfium_ver:
        type: string
        default: 'latest'
      test_on_host:
        type: boolean
        default: true
      ref:
        type: string
        default: ''
      replicate_tag:
        type: string
        default: ''
  workflow_dispatch:
    inputs: *reusable_inputs

defaults:
  run:
    shell: bash
permissions: {}

jobs:
  
  build:
    name: Build ${{ inputs.pbin_target }} on ${{ inputs.runner_os }}
    permissions:
      contents: read  # recommended by checkout and setup-python actions
    outputs:
      artifact_id: ${{ steps.upload-artifact.outputs.artifact-id }}
    
    runs-on: ${{ inputs.runner_os }}
    steps:
      
      - name: Check out pypdfium2 (deep)
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0  # for git describe
          persist-credentials: false
          ref: ${{ inputs.ref || github.ref_name }}
      
      - name: Prepare
        uses: ./.github/actions/prepare_step
        with:
          replicate_tag: ${{ inputs.replicate_tag }}
          py_vers: ${{ inputs.py_vers }}
          py_arch: ${{ inputs.pbin_target == 'windows_x86' && 'x86' || '' }}
          pip_install: -U -r req/setup.txt
      
      - name: Build wheel
        run: |
          python3 setupsrc/emplace.py
          USE_TARBALL_LICENSES=1 python3 -m build -wxn
        env:
          PDFIUM_PLATFORM: "${{ inputs.pbin_target }}:${{ inputs.pdfium_ver }}"
      
      - name: Upload wheel as artifact
        id: upload-artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: dist/*.whl
          name: "dist-pbin-${{ inputs.pbin_target }}-${{ inputs.runner_os }}"
      
      - name: Inspect build
        uses: ./.github/actions/inspect_step
        with:
          runner_os: ${{ inputs.runner_os }}
          dll_glob: ${{ format('data/{0}/*pdfium.*', inputs.pbin_target) }}
          auditwheel: ${{ (startsWith(inputs.pbin_target, 'linux_') && !startsWith(inputs.pbin_target, 'linux_musl_') && !startsWith(inputs.pbin_target, 'linux_mips')) || '' }}
      
      - name: Test wheel
        uses: ./.github/actions/test_step
        # https://github.com/actions/runner/issues/2238 ...
        with:
          runner_os: ${{ inputs.runner_os }}
          py_vers: ${{ inputs.py_vers }}
          test_on_host: ${{ inputs.test_on_host || '' }}
          docker: ${{ startsWith(inputs.pbin_target, 'linux_') || '' }}
          windows_32bit: ${{ inputs.pbin_target == 'windows_x86' || '' }}
          mac_consider_rosetta: ${{ inputs.pbin_target == 'darwin_x64' || inputs.pbin_target == 'darwin_univ2' || '' }}
  
  test_other:
    name: 'Test on another runner - ${{ inputs.test_os }}'
    if: ${{ inputs.test_os }}
    needs: build
    permissions:
      contents: read  # needed by called workflow
    
    uses: ./.github/workflows/test_one.yaml
    with:
      runner_os: ${{ inputs.test_os }}
      artifact_id: ${{ needs.build.outputs.artifact_id }}
      py_vers: ${{ inputs.testos_py_vers || inputs.py_vers }}
      ref: ${{ inputs.ref }}
