# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Sourcebuild Native

on:
  workflow_dispatch:
    inputs:
      pdfium_ver:
        type: string
        default: ''
      py_ver:
        type: string
        default: '3.14'
      vendor:
        type: string
        default: 'icu'
      test_pdfium:
        type: boolean
        default: true
      gcc:
        type: boolean
        default: true
      clang:
        type: boolean
        default: true

# TODO Windows/macOS native?

jobs:
  
  build:
    
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'ubuntu-24.04-arm']
        compiler: ['gcc', 'clang']
        include:
          - compiler: gcc
            condition: ${{ inputs.gcc }}
          - compiler: clang
            condition: ${{ inputs.clang }}
    
    uses: ./.github/workflows/sbuild_one_native.yaml
    if: ${{ matrix.condition }}
    with:
      os: ${{ matrix.os }}
      compiler: ${{ matrix.compiler }}
      pdfium_ver: ${{ inputs.pdfium_ver }}
      py_ver: ${{ inputs.py_ver }}
      vendor: ${{ inputs.vendor }}
      test_pdfium: ${{ inputs.test_pdfium }}
