# SPDX-FileCopyrightText: 2025 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Sourcebuild (Test-only)

# TODO ...

# matrix:
#   # On GH actions, macOS <=13 is Intel, whereas macOS >=14 will be ARM64
#   # Google's toolchain doesn't seem to run on Linux/Windows arm64 natively. The toolchain-free build (or cross-compilation from x86_64) should work, though.
#   # 'ubuntu-24.04-arm', 'windows-11-arm'
#   os: ['ubuntu-latest', 'macos-13', 'macos-latest', 'windows-latest']
#   build_mode: ['toolchained']
#   include:
#     - os: 'ubuntu-latest'
#       build_mode: 'syslibs'
#     - os: 'ubuntu-latest'
#       build_mode: 'native-gcc'
#     - os: 'ubuntu-24.04-arm'
#       build_mode: 'native-gcc'
#     - os: 'ubuntu-latest'
#       build_mode: 'native-clang'
#     - os: 'ubuntu-24.04-arm'
#       build_mode: 'native-clang'
