# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Sourcebuild One

on:
  workflow_call:
    inputs: &reusable_inputs
      os:
        type: string
        required: true
      py_ver:
        type: string
        default: '3.14'
      pdfium_ver:
        type: string
        default: ''
      target_cpu:
        type: string
        default: ''
      target_os:
        type: string
        default: ''
      build_params:
        type: string
        default: ''
      tag:
        type: string
        default: ''
      branch:
        type: string
        default: ''
      repo_tag:
        type: string
        default: ''
      custom_clang:
        type: boolean
        default: false
      condition:
        type: boolean
        default: true
  workflow_dispatch:
    inputs: *reusable_inputs

defaults:
  run:
    shell: bash

jobs:
  
  build:
    runs-on: ${{ inputs.os }}
    if: ${{ inputs.condition }}
    
    steps:
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.py_ver }}
      
      - name: Check out pypdfium2 repository
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          persist-credentials: false
          fetch-depth: 0  # for git describe
          ref: ${{ inputs.branch || github.ref_name }}
      
      - name: Create pypdfium2 tag (optional)
        if: ${{ inputs.repo_tag }}
        run: |
          git config user.email "geisserml@gmail.com"
          git config user.name "geisserml"
          git tag -a "$REPO_TAG" -m "Autorelease"
        env:
          REPO_TAG: ${{ inputs.repo_tag }}
      
      - name: Install custom clang
        if: ${{ inputs.custom_clang }}
        run: ./utils/install-static-clang.sh --install-only
      
      - name: Install Python deps
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -U -r req/setup.txt -r req/test.txt
      
      - name: Update package list
        if: ${{ startsWith(inputs.os, 'ubuntu') && (inputs.target_cpu || endsWith(inputs.os, '-arm')) }}
        run: sudo apt-get update
      
      - name: Install Linux/Android cross deps
        if: ${{ startsWith(inputs.os, 'ubuntu') && inputs.target_cpu }}
        run: |
          PACKAGES=$(python3 ./utils/get_cross_deps.py $TARGET_CPU)
          echo $PACKAGES; sudo apt-get install -y $PACKAGES
          #ls -l /usr/bin |grep -E '\-(gcc|g\+\+|ar|nm|readelf)(-[0-9.]+)?$'
        env:
          TARGET_CPU: ${{ inputs.target_cpu }}
      
      # - name: Create symlinks if needed
      #   if: ${{ inputs.target_cpu == 'mips64el' }}
      #   run: |
      #     sudo ln -s /usr/bin/mips64el-linux-gnuabi64-g++-13 /usr/local/bin/mips64el-linux-gnuabi64-g++
      #     sudo ln -s /usr/bin/mips64el-linux-gnuabi64-gcc-13 /usr/local/bin/mips64el-linux-gnuabi64-gcc
      
      - name: Install Linux native deps  # fallback
        if: ${{ startsWith(inputs.os, 'ubuntu') && endsWith(inputs.os, '-arm') }}
        run: |
          sudo apt-get install -y ninja-build  # generate-ninja
          python3 -m pip install -r req/gn.txt
          #python3 -c "from gn_dist import GN; print(str(GN.parent))" >> $GITHUB_PATH
      
      # GHA windows-2025 image Windows SDK is incomplete, lacks "Debugging Tools for Windows" feature requested by PDFium's build system for the cross targets. So we're using this action to install the SDK properly.
      - name: Install Windows cross deps
        if: ${{ startsWith(inputs.os, 'windows') && !endsWith(inputs.os, '-arm') && inputs.target_cpu }}
        uses: ChristopheLav/windows-sdk-install@v1
        with:
          version-sdk: 26100
          features: 'OptionId.WindowsDesktopDebuggers'
      
      - name: Build PDFium (toolchained)
        run: python3 ./setupsrc/build_toolchained.py $VERSION_PARAM $CPU_PARAM $OS_PARAM $BUILD_PARAMS
        env:
          VERSION_PARAM: ${{ inputs.pdfium_ver && format('--version {0}', inputs.pdfium_ver) }}
          CPU_PARAM: ${{ inputs.target_cpu && format('--target-cpu {0}', inputs.target_cpu) }}
          OS_PARAM: ${{ inputs.target_os && format('--target-os {0}', inputs.target_os) }}
          BUILD_PARAMS: ${{ inputs.build_params }}
      
      - name: Show binary info
        run: file ./data/sourcebuild/*.{so,dylib,dll}
      
      - name: Build wheel
        run: python3 -m build -wxn
        env:
          PDFIUM_PLATFORM: sourcebuild
          CROSS_TAG: ${{ inputs.tag }}  # optional
      
      - name: Upload wheel as artifact
        uses: actions/upload-artifact@v7
        with:
          path: ./dist/*.whl
          name: sbuild_${{ inputs.target_os || inputs.os }}${{ inputs.target_cpu && format('_{0}', inputs.target_cpu) }}
      
      - name: Install and test wheel
        if: ${{ !(inputs.target_cpu || inputs.target_os) }}
        run: |
          python3 -m pip install ./dist/*.whl
          pypdfium2 -v
          python3 -m pytest tests/
      
      - name: On Linux, run auditwheel (informational)
        if: ${{ startsWith(inputs.os, 'ubuntu') && !inputs.target_os && inputs.target_cpu != 'mips64el' }}
        run: |
          python3 -m pip install -U auditwheel
          python3 -m auditwheel show dist/*.whl
      
      - name: On macOS, run vtool (informational)
        if: ${{ startsWith(inputs.os, 'macos') }}
        run: vtool -show-build ./data/sourcebuild/libpdfium.dylib
