# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: SBLD one
on:
  workflow_call:
    inputs: &reusable_inputs
      runner_os:
        type: string
        required: true
      test_os:
        type: string
        default: ''
      py_vers:
        type: string
        default: '3.14'
      pdfium_ver:
        type: string
        default: ''
      target_cpu:
        type: string
        default: ''
      target_os:
        type: string
        default: ''
      build_params:
        type: string
        default: ''
      custom_clang:
        type: boolean
        default: false
      wheel_tag:
        type: string
        default: ''
      ref:
        type: string
        default: ''
      replicate_tag:
        type: string
        default: ''
  workflow_dispatch:
    inputs: *reusable_inputs

defaults:
  run:
    shell: bash
permissions: {}

jobs:
  
  build:
    name: Build ${{ inputs.target_os || inputs.runner_os }} ${{ inputs.target_cpu }}
    permissions:
      contents: read  # recommended by checkout and setup-python actions
    outputs:
      artifact_id: ${{ steps.upload-artifact.outputs.artifact-id }}
    
    runs-on: ${{ inputs.runner_os }}
    steps:
      
      - name: Check out pypdfium2 (deep)
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0  # for git describe
          persist-credentials: false
          ref: ${{ inputs.ref || github.ref_name }}
      
      - name: Prepare
        uses: ./.github/actions/prepare_step
        with:
          replicate_tag: ${{ inputs.replicate_tag }}
          py_vers: ${{ inputs.py_vers }}
          py_arch: ${{ (startsWith(inputs.runner_os, 'windows') && inputs.target_cpu == 'x86') && 'x86' || '' }}
          pip_install: -U -r req/setup.txt
      
      - name: Install custom clang
        if: ${{ inputs.custom_clang }}
        run: bash utils/install-static-clang.sh -m install-only
      
      - name: Update package list
        if: ${{ startsWith(inputs.runner_os, 'ubuntu') && (inputs.target_cpu || endsWith(inputs.runner_os, '-arm')) }}
        run: sudo apt-get update
      
      - name: Install Linux/Android cross deps
        if: ${{ startsWith(inputs.runner_os, 'ubuntu') && inputs.target_cpu }}
        run: |
          PACKAGES=$(python3 utils/get_cross_deps.py $TARGET_CPU $RUNNER_OS)
          echo $PACKAGES; sudo apt-get install -y $PACKAGES
          ls -l /usr/bin |grep -E '\-(gcc|g\+\+|ar|nm|readelf)(-[0-9.]+)?$'
        env:
          RUNNER_OS: ${{ inputs.runner_os }}
          TARGET_CPU: ${{ inputs.target_cpu }}
      
      - name: Install Linux native deps  # fallback
        if: ${{ startsWith(inputs.runner_os, 'ubuntu') && endsWith(inputs.runner_os, '-arm') }}
        run: |
          sudo apt-get install -y ninja-build  # generate-ninja
          python3 -m pip install -r req/gn.txt
          #python3 -c "from gn_dist import GN; print(str(GN.parent))" >> $GITHUB_PATH
      
      # GHA windows-2025 image Windows SDK is incomplete, lacks "Debugging Tools for Windows" feature requested by PDFium's build system for the cross targets. So we're using this action to install the SDK properly.
      - name: Install Windows cross deps
        if: ${{ startsWith(inputs.runner_os, 'windows') && !endsWith(inputs.runner_os, '-arm') && inputs.target_cpu }}
        uses: ChristopheLav/windows-sdk-install@aceebd61475568479ce68465d0849f5de9a0bfe9 # v1.0.5
        with:
          version-sdk: 26100
          features: 'OptionId.WindowsDesktopDebuggers'
      
      - name: Build PDFium (toolchained)
        run: python3 ./setupsrc/build_toolchained.py $VERSION_PARAM $CPU_PARAM $OS_PARAM $GCC_PARAM $BUILD_PARAMS
        env:
          VERSION_PARAM: ${{ inputs.pdfium_ver && format('--version {0}', inputs.pdfium_ver) }}
          CPU_PARAM: ${{ inputs.target_cpu && format('--target-cpu {0}', inputs.target_cpu) }}
          OS_PARAM: ${{ inputs.target_os && format('--target-os {0}', inputs.target_os) }}
          BUILD_PARAMS: ${{ inputs.build_params }}
      
      - name: Build wheel
        run: python3 -m build -wxn
        env:
          PDFIUM_PLATFORM: sourcebuild
          CROSS_TAG: ${{ inputs.wheel_tag }}  # optional
      
      - name: Upload wheel as artifact
        id: upload-artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: dist/*.whl
          name: "sbuild-${{ inputs.target_os || inputs.runner_os }}${{ inputs.target_cpu && format('_{0}', inputs.target_cpu) }}"
      
      # https://github.com/actions/runner/issues/2238 ...
      # Bear in mind: some fields, e.g. continue-on-error, require an actual bool (check GH docs).
      # In that case, need to use fromJSON() in the called action, and not map to empty string here.
      # Using empty/non-empty string as bool substitute should be OK for if conditionals though.
      
      - name: Inspect build
        uses: ./.github/actions/inspect_step
        with:
          runner_os: ${{ inputs.runner_os }}
          auditwheel: ${{ !(inputs.target_os || startsWith(inputs.target_cpu, 'mips')) || '' }}
          dll_glob: 'data/sourcebuild/*pdfium.*'
      
      - name: Test wheel
        uses: ./.github/actions/test_step
        with:
          runner_os: ${{ inputs.runner_os }}
          py_vers: ${{ inputs.py_vers }}
          test_on_host: ${{ !(inputs.target_os || inputs.target_cpu) || '' }}
          docker: ${{ !(inputs.target_os || inputs.target_cpu == 'mipsel') || '' }}
          windows_32bit: ${{ startsWith(inputs.runner_os, 'windows') && inputs.target_cpu == 'x86' || '' }}
          mac_emulate_intel: ${{ inputs.target_cpu && !endsWith(inputs.runner_os, '-intel') || '' }}
  
  test_other:
    name: 'Test on another runner - ${{ inputs.test_os }}'
    if: ${{ inputs.test_os }}
    needs: build
    permissions:
      contents: read  # needed by called workflow
    
    uses: ./.github/workflows/test_one.yaml
    with:
      runner_os: ${{ inputs.test_os }}
      artifact_id: ${{ needs.build.outputs.artifact_id }}
      py_vers: ${{ inputs.py_vers }}
      ref: ${{ inputs.ref }}
