# SPDX-FileCopyrightText: 2025 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Sourcebuild One Native

on:
  workflow_call:
    inputs:
      os:
        type: string
      build_mode:
        type: string
      py_version:
        type: string
        default: '3.12'

defaults:
  run:
    shell: bash

jobs:
  
  build:
    runs-on: ${{ inputs.os }}
    
    steps:
      
      - uses: extractions/setup-just@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.py_version }}
      
      - name: Check out pypdfium2 repository
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          # fetch-depth: 0  # for git describe
      
      - name: Install python deps
        run: python3 -m pip install -U -r req/setup.txt -r req/test.txt
      
      - name: Install deps for native/syslibs build
        if: ${{ startsWith(inputs.build_mode, 'native') || inputs.build_mode == 'syslibs' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype-dev liblcms2-dev libjpeg-dev libopenjp2-7-dev libpng-dev zlib1g-dev libicu-dev libtiff-dev
      
      - name: Install deps for native build
        if: ${{ startsWith(inputs.build_mode, 'native') }}
        run: sudo apt-get install -y generate-ninja ninja-build libglib2.0-dev
      
      - name: Build PDFium (toolchained, with syslibs)
        if: ${{ inputs.build_mode == 'syslibs' }}
        run: python3 ./setupsrc/pypdfium2_setup/build_toolchained.py --use-syslibs
      
      - name: Build PDFium (native, gcc)
        if: ${{ inputs.build_mode == 'native-gcc' }}
        run: python3 ./setupsrc/pypdfium2_setup/build_native.py --compiler gcc --test
      
      - name: Build PDFium (native, clang)
        if: ${{ inputs.build_mode == 'native-clang' }}
        run: |
          VERSION=18
          ARCH=$(uname -m)
          sudo apt-get install -y llvm lld
          sudo ln -s /usr/lib/clang/$VERSION/lib/linux /usr/lib/clang/$VERSION/lib/$ARCH-unknown-linux-gnu
          sudo ln -s /usr/lib/clang/$VERSION/lib/linux/libclang_rt.builtins-$ARCH.a /usr/lib/clang/$VERSION/lib/linux/libclang_rt.builtins.a
          python3 ./setupsrc/pypdfium2_setup/build_native.py --compiler clang --test
      
      # no point packing/uploading a wheel, as native/syslibs builds are host-specific
      
      - name: Install
        run: python3 -m pip install .
        env:
          PDFIUM_PLATFORM: sourcebuild
      
      - name: Test
        run: |
          pypdfium2 -v
          just test
