# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Sourcebuild Native

on:
  workflow_dispatch:
    inputs:
      pdfium_ver:
        type: string
        default: ''
      py_ver:
        type: string
        default: '3.14'
      vendor:
        type: string
        default: 'icu'
      test_pdfium:
        type: boolean
        default: true
      linux_native_gcc:
        type: boolean
        default: true
      linux_native_clang:
        type: boolean
        default: true

# TODO Windows/macOS native?

jobs:
  
  linux_x64_native_gcc:
    if: ${{ inputs.linux_native_gcc }}
    uses: ./.github/workflows/sbuild_one_native.yaml
    with:
      os: ubuntu-latest
      compiler: gcc
      pdfium_ver: ${{ inputs.pdfium_ver }}
      py_ver: ${{ inputs.py_ver }}
      vendor: ${{ inputs.vendor }}
      test_pdfium: ${{ inputs.test_pdfium }}
  
  linux_arm64_native_gcc:
    if: ${{ inputs.linux_native_gcc }}
    uses: ./.github/workflows/sbuild_one_native.yaml
    with:
      os: ubuntu-24.04-arm
      compiler: gcc
      pdfium_ver: ${{ inputs.pdfium_ver }}
      py_ver: ${{ inputs.py_ver }}
      vendor: ${{ inputs.vendor }}
      test_pdfium: ${{ inputs.test_pdfium }}
  
  linux_x64_native_clang:
    if: ${{ inputs.linux_native_clang }}
    uses: ./.github/workflows/sbuild_one_native.yaml
    with:
      os: ubuntu-latest
      compiler: clang
      pdfium_ver: ${{ inputs.pdfium_ver }}
      py_ver: ${{ inputs.py_ver }}
      vendor: ${{ inputs.vendor }}
      test_pdfium: ${{ inputs.test_pdfium }}
  
  linux_arm64_native_clang:
    if: ${{ inputs.linux_native_clang }}
    uses: ./.github/workflows/sbuild_one_native.yaml
    with:
      os: ubuntu-24.04-arm
      compiler: clang
      pdfium_ver: ${{ inputs.pdfium_ver }}
      py_ver: ${{ inputs.py_ver }}
      vendor: ${{ inputs.vendor }}
      test_pdfium: ${{ inputs.test_pdfium }}
