# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Sourcebuild

on:
  workflow_dispatch:
    inputs:
      linux:
        type: boolean
        default: true
      macos:
        type: boolean
        default: true
      windows:
        type: boolean
        default: true
      android:
        type: boolean
        default: true
      targets_main:
        type: boolean
        default: true
      targets_test:
        type: boolean
        default: false
      pdfium_ver:
        type: string
        default: ''
      py_ver:
        type: string
        default: '3.14'

jobs:
  
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          
          - os: ubuntu-26.04
            condition: ${{ inputs.linux && inputs.targets_main }}
            tag: manylinux_2_17_x86_64.manylinux2014_x86_64
          
          - os: ubuntu-26.04
            condition: ${{ inputs.linux && inputs.targets_main }}
            target_cpu: x86
            tag: manylinux_2_17_i686.manylinux2014_i686
          
          - os: ubuntu-26.04
            condition: ${{ inputs.linux && inputs.targets_main }}
            target_cpu: arm64
            tag: manylinux_2_17_aarch64.manylinux2014_aarch64
          
          - os: ubuntu-26.04
            condition: ${{ inputs.linux && inputs.targets_main }}
            target_cpu: arm
            tag: manylinux_2_17_armv7l.manylinux2014_armv7l
          
          - os: ubuntu-26.04
            condition: ${{ inputs.linux && inputs.targets_main }}
            target_cpu: ppc64
            tag: manylinux_2_17_ppc64le.manylinux2014_ppc64le
          
          - os: ubuntu-24.04  # dont't use 26.04, it lacks GCC cross for MIPS :(
            condition: ${{ inputs.linux && inputs.targets_main }}
            target_cpu: mips64el
            tag: manylinux_2_17_mips64le.manylinux2014_mips64le
          
          - os: ubuntu-24.04  # dto.
            condition: ${{ inputs.linux && inputs.targets_main }}
            target_cpu: mipsel
            tag: manylinux_2_17_mipsle.manylinux2014_mipsle
            docker_test: false
          
          - os: ubuntu-24.04-arm  # don't use 26.04, due to glibc req (see below)
            condition: ${{ inputs.linux && inputs.targets_test }}
            py_ver: '3.13'
            # if we don't use the sysroot or an older container, the glibc requirement is high
            # see below for an alternative approach that uses the sysroot on aarch64 natively
            tag: manylinux_2_38_aarch64
          
          - os: ubuntu-26.04-arm
            condition: ${{ inputs.linux && inputs.targets_test }}
            py_ver: '3.13'
            build_params: '--use-sysroot --clang-path /opt/clang'
            custom_clang: true
            tag: manylinux_2_17_aarch64.manylinux2014_aarch64
          
          - os: macos-latest  # arm64 host
            condition: ${{ inputs.macos && inputs.targets_main }}
            target_cpu: x64
            tag: macosx_12_0_x86_64
          
          - os: macos-latest
            condition: ${{ inputs.macos && inputs.targets_main }}
            tag: macosx_12_0_arm64
          
          # test macOS the other way round while we still can
          - os: macos-15-intel
            condition: ${{ inputs.macos && inputs.targets_test }}
            tag: macosx_12_0_x86_64
          
          - os: macos-15-intel
            condition: ${{ inputs.macos && inputs.targets_test }}
            target_cpu: arm64
            tag: macosx_12_0_arm64
          
          - os: windows-latest  # amd64
            condition: ${{ inputs.windows && inputs.targets_main }}
          
          - os: windows-latest
            condition: ${{ inputs.windows && inputs.targets_main }}
            target_cpu: arm64
            tag: win_arm64
          
          - os: windows-latest
            condition: ${{ inputs.windows && inputs.targets_main }}
            target_cpu: x86
            tag: win32
          
          - os: windows-11-vs2026-arm
            condition: ${{ inputs.windows && inputs.targets_test }}
          
          - os: ubuntu-26.04
            condition: ${{ inputs.android && inputs.targets_main }}
            target_os: android
            target_cpu: arm64
            tag: android_23_arm64_v8a
          
          - os: ubuntu-26.04
            condition: ${{ inputs.android && inputs.targets_main }}
            target_os: android
            target_cpu: arm
            tag: android_23_armeabi_v7a
    
    uses: ./.github/workflows/sbuild_one.yaml
    with:
      os: ${{ matrix.os }}
      condition: ${{ matrix.condition }}
      target_cpu: ${{ matrix.target_cpu }}
      target_os: ${{ matrix.target_os }}
      tag: ${{ matrix.tag }}
      pdfium_ver: ${{ inputs.pdfium_ver }}
      py_ver: ${{ matrix.py_ver || inputs.py_ver }}
      custom_clang: ${{ matrix.custom_clang || false }}
      build_params: ${{ matrix.build_params }}
      docker_test: ${{ matrix.docker_test == '' && true || matrix.docker_test }}
