# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Test Setup
on:
  workflow_call:
    inputs: &reusable_inputs
      upload_data:
        type: boolean
        default: false
      # may_use_refbindings:
      #   type: boolean
      #   default: false
  workflow_dispatch:
    inputs: *reusable_inputs

defaults:
  run:
    shell: bash

jobs:
  
  test_setup:
    
    strategy:
      fail-fast: false
      matrix:
        # stick with ubuntu-24.04 for now so we can keep testing python 3.9
        os: ['ubuntu-24.04', 'ubuntu-24.04-arm', 'macos-15-intel', 'macos-latest', 'windows-latest', 'windows-11-vs2026-arm']
        py: ['3.9', '3.11', '3.14']  # '3.10', '3.12', '3.13',
        exclude:
          # not supported by setup-python action
          - os: windows-11-vs2026-arm
            py: '3.9'
          # - os: windows-11-vs2026-arm
          #   py: '3.10'
    
    runs-on: ${{ matrix.os }}
    permissions: {}
    
    steps:
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py }}
      
      - name: Check out pypdfium2 repository
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0  # for git describe in "Build docs" step
          persist-credentials: false
      
      # TODO(consider) run test suite after each way of installing?
      
      - name: Test various install strategies
        run: |
          python3 -m pip install -U pip
          # isolated
          python3 -m pip install -v .
          python3 -m pip install -v -e .
          # non-isolated
          python3 -m pip install -U -r req/setup.txt -r req/test.txt -r req/docs.txt
          python3 -m pip install -v --no-build-isolation .
          python3 -m pip install -v --no-build-isolation -e .
        # env:
        #   PDFIUM_BINDINGS: ${{ inputs.may_use_refbindings && startsWith(matrix.os, 'windows') && 'reference' || '' }}
      
      - name: Upload generated bindings for inspection
        if: ${{ inputs.upload_data }}
        uses: actions/upload-artifact@v7
        with:
          name: bindings_${{ matrix.os }}_py${{ matrix.py }}
          path: |
            data/bindings/bindings.py
      
      - name: Build docs
        run: python3 -m sphinx -b html docs/source docs/build/html
      
      - name: Run test suite
        run: python3 -m pytest tests/ -sv
