# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Test PyPI Release
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
permissions: {}

jobs:
  test-release:
    name: Test PyPI Release
    permissions:
      contents: read  # recommended by checkout and setup-python actions
    strategy:
      fail-fast: false
      matrix:
        # stick with ubuntu-24.04 for now so we can keep testing python 3.8
        os: ['ubuntu-24.04', 'ubuntu-24.04-arm', 'macos-15-intel', 'macos-latest', 'windows-latest', 'windows-11-arm']
        py: ['3.8', '3.11', '3.14']  # '3.9', '3.10', '3.12', '3.13',
        include:
          # on windows with python 3.8, the `python3` executable does not seem to exit for some reason
          - os: windows-latest
            py: '3.8'
            initial_python: python
        exclude:
          # not available with setup-python action
          - os: windows-11-arm
            py: '3.8'
          # - os: windows-11-arm
          #   py: '3.9'
          # - os: windows-11-arm
          #   py: '3.10'
    
    runs-on: ${{ matrix.os }}
    steps:
      
      - name: Check out pypdfium2 (deep)
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.py }}
      
      - name: Create venv & install pip packages
        uses: ./.github/actions/install_step
        with:
          runner_os: ${{ matrix.os }}
          pip_install: -U -r req/converters.txt -r req/test.txt
          pip_install_hot: --pre pypdfium2
          initial_python: ${{ matrix.initial_python || 'python3' }}
      
      - name: Check out the right tag
        run: |
          TAG=$(python3 -c "from pypdfium2.version import *; print(PYPDFIUM_INFO.tag)")
          git checkout "$TAG"
      
      - name: Run tests
        run: |
          pypdfium2 --version
          python3 -m pytest tests/
