# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Test PyPI Release
on:
  workflow_dispatch:
    inputs:
      use_sdist:
        type: boolean
        default: false

defaults:
  run:
    shell: bash
permissions: {}

jobs:
  test-release:
    name: Test PyPI Release
    permissions:
      contents: read  # recommended by checkout and setup-python actions
    strategy:
      fail-fast: false
      matrix:
        # stick with ubuntu-24.04 for now so we can keep testing python 3.8
        os: ['ubuntu-24.04', 'ubuntu-24.04-arm', 'macos-15-intel', 'macos-latest', 'windows-latest', 'windows-11-arm']
        py: ['3.8', '3.11', '3.14']  # '3.9', '3.10', '3.12', '3.13',
        include:
          # on windows with python 3.8, the `python3` executable does not seem to exit for some reason
          - os: windows-latest
            py: '3.8'
            initial_python: python
        exclude:
          # not available with setup-python action
          - os: windows-11-arm
            py: '3.8'
          # - os: windows-11-arm
          #   py: '3.9'
          # - os: windows-11-arm
          #   py: '3.10'
    
    runs-on: ${{ matrix.os }}
    steps:
      
      - name: Check out pypdfium2 (deep)
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.py }}
      
      - name: Create venv
        uses: ./.github/actions/venv_step
        with:
          initial_python: ${{ matrix.initial_python || 'python3' }}
      
      # The project itself must be exempted from dependency cooldown, we unconditionally want to be able to test the latest version here, including beta.
      - name: Install pip packages
        run: |
          echo "Cooldown: ${PIP_UPLOADED_PRIOR_TO:?}"
          pip install -U --group converters --group test $GROUP_SETUP
          env -u PIP_UPLOADED_PRIOR_TO pip install --no-deps --no-build-isolation --pre pypdfium2 $WHEEL_CTRL pypdfium2
        env:
          GROUP_SETUP: ${{ inputs.use_sdist && '--group setup' || '' }}
          WHEEL_CTRL: ${{ inputs.use_sdist && '--no-binary' || '--only-binary' }}
      
      - name: Check out the right tag
        run: |
          TAG=$(python3 -c "from pypdfium2.version import *; print(PYPDFIUM_INFO.tag)")
          git checkout "$TAG"
      
      - name: Run tests
        run: |
          pypdfium2 --version
          python3 -m pytest tests/
