# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Test Native Build
on:
  workflow_dispatch:
    inputs:
      py_ver:
        type: string
        default: '3.14'
      pdfium_ver:
        type: string
        default: ''
      vendor:
        type: string
        default: 'icu'
      gcc:
        type: boolean
        default: true
      clang:
        type: boolean
        default: true
      x64:
        type: boolean
        default: true
      arm64:
        type: boolean
        default: true
      test_pdfium:
        type: boolean
        default: true

permissions: {}

jobs:
  # TODO Windows/macOS native?
  build:
    permissions:
      contents: read  # needed by called workflow
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04', 'ubuntu-24.04-arm']
        compiler: ['gcc', 'clang']
        include:
          - compiler: gcc
            cc_condition: ${{ inputs.gcc }}
          - compiler: clang
            cc_condition: ${{ inputs.clang }}
          - os: ubuntu-24.04
            os_condition: ${{ inputs.x64 }}
          - os: ubuntu-24.04-arm
            os_condition: ${{ inputs.arm64 }}
    
    uses: ./.github/workflows/test_native_build_one.yaml
    with:
      os: ${{ matrix.os }}
      condition: ${{ matrix.cc_condition && matrix.os_condition }}
      compiler: ${{ matrix.compiler }}
      py_ver: ${{ inputs.py_ver }}
      pdfium_ver: ${{ inputs.pdfium_ver }}
      vendor: ${{ inputs.vendor }}
      test_pdfium: ${{ inputs.test_pdfium }}
