# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

# Separate trigger workflow because we can't configure inputs for scheduled workflow runs (and don't want publish enabled by default in the main workflow)

name: Trigger main release
on:
  # NOTE Schedule currently suspended, to preserve PyPI disk space. Manually dispatch releases as needed.
  # # https://github.com/bblanchon/pdfium-binaries/blob/master/.github/workflows/trigger.yml
  # # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  # # https://crontab.guru/
  # schedule:
  #   - cron: '0 4 10 * *'  # monthly, 10th day
  workflow_dispatch:

jobs:
  
  trigger:
    runs-on: ubuntu-26.04
    
    steps:
      # IMPORTANT Need to use workflow dispatch here, not reusable workflow call.
      # This is because pypa/gh-action-pypi-publish actually fails when nested in a reusable workflow call. (This broke PyPI upload of our 5.10.0 release. For some reason, TestPyPI upload passed, probably because it has attestations disabled...)
      - name: Trigger
        uses: benc-uk/workflow-dispatch@31e2b3319479a63f0ab15bf800eff9e913504e26  # v1.3.2
        with:
          workflow: main.yaml
          inputs: |
            {
              "runner": "ubuntu-26.04"
              "py_ver": "3.14",
              "test": "true",
              "augment": "true",
              "publish": "true",
              "gh_pages": "true",
              "conda": "true",
            }
