# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Trigger conda_raw release
on:
  schedule:
    # pdfium-binaries triggers conda on the first Monday of month at 4 o'clock UTC, so we'll want to rebuild after that, but before the next main release where we want to use the package
    - cron: '0 4 8 * *'  # monthly, 8th day
  workflow_dispatch:

permissions: {}

jobs:
  conda_raw_release:
    permissions:  # needed by called workflow
      contents: read
    uses: ./.github/workflows/conda.yaml
    with:
      package: raw
      new_only: true
      test: true
      publish: true
      actually_publish: false  # XXX
    secrets:
      anaconda_api_token: ${{ secrets.ANACONDA_API_TOKEN }}
