# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

# Separate trigger workflow because we can't configure inputs for scheduled workflow runs (and don't want publish enabled by default in the main workflow)

name: Trigger main release
on:
  # NOTE Schedule currently suspended, to preserve PyPI disk space. Manually dispatch releases as needed.
  # # https://github.com/bblanchon/pdfium-binaries/blob/master/.github/workflows/trigger.yml
  # # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  # # https://crontab.guru/
  # schedule:
  #   - cron: '0 4 10 * *'  # monthly, 10th day
  workflow_dispatch:

permissions: {}

jobs:
  
  trigger:
    runs-on: ubuntu-26.04
    permissions:
      actions: write
    
    steps:
      # IMPORTANT Need to use workflow dispatch here, not reusable workflow call.
      # This is because pypa/gh-action-pypi-publish actually fails when nested in a reusable workflow call. (This broke PyPI upload of our 5.10.0 release. For some reason, TestPyPI upload passed, probably because it has attestations disabled...)
      # TODO unlock actually_publish
      - name: Trigger
        run: |
          gh workflow run main.yaml -R pypdfium2-team/pypdfium2 --ref "$REF_NAME" --json <<EOF
          {
            "runner_os": "ubuntu-26.04",
            "py_vers": "3.11 3.14",
            "profile": "default",
            "pbin": "",
            "sbuild": "",
            "cibw": "",
            "autorelease": "true",
            "sdist": "true",
            "conda": "true",
            "gh_pages": "true",
            "publish": "true",
            "actually_publish": "false"
          }
          EOF
        env:
          GH_TOKEN: ${{ github.token }}
          REF_NAME: ${{ github.ref_name }}
