# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

name: Trigger main release
on:
  # NOTE Schedule currently suspended. Manually dispatch releases as needed.
  # # https://github.com/bblanchon/pdfium-binaries/blob/master/.github/workflows/trigger.yml
  # # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  # # https://crontab.guru/
  # schedule:
  #   - cron: '0 4 10 * *'  # monthly, 10th day
  workflow_dispatch:

permissions: {}
jobs:
  
  # Need to use workflow dispatch here. pypa/gh-action-pypi-publish does not support the reusable workflow call model. (This broke PyPI upload of our 5.10.0 release. TestPyPI did not catch the issue.)
  trigger:
    name: Dispatch release workflow
    permissions:
      actions: write  # allow workflow dispatch
    
    runs-on: ubuntu-26.04
    steps:
      # TODO unlock actually_publish
      - name: Dispatch workflow with GH CLI
        run: |
          gh workflow run main.yaml -R "$REPOSITORY" --ref "$REF_NAME" --json <<EOF
          {
            "runner_os": "ubuntu-26.04",
            "py_vers": "3.11 3.14",
            "profile": "default",
            "pbin": "",
            "sbuild": "",
            "cibw": "",
            "autorelease": "true",
            "sdist": "true",
            "conda": "true",
            "gh_pages": "true",
            "publish": "true",
            "actually_publish": "false"
          }
          EOF
        env:
          GH_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
          REF_NAME: ${{ github.ref_name }}
